/**
 * Created by Xinhe on 2017/11/18.
 */

export const MESSAGE_RECEIVE = 'MESSAGE_RECEIVE'
export const EMPTY_MESSAGES = 'EMPTY_MESSAGES'
export const CHANGE_SOCKET_STATUS = 'CHANGE_SOCKET_STATUS'
export const CLEAR_TASK_MESSAGES= 'CLEAR_TASK_MESSAGES'
export const CLEAR_SUBTASK_MESSAGES= 'CLEAR_SUBTASK_MESSAGES'


export const CHANGE_SUBTASK_STATUS= 'CHANGE_SUBTASK_STATUS'

export const SET_TASKS = 'SET_TASKS'
export const SET_SCRIPTS = 'SET_SCRIPTS'
export const SET_SERVERS = 'SET_SERVERS'

export const SET_TASK = 'SET_TASK'
export const DELETE_TASK ='DELETE_TASK'
