/**
 * Created by Xinhe on 2017/11/18.
 */

export const MESSAGE_RECEIVE = 'MESSAGE_RECEIVE'
export const EMPTY_MESSAGES = 'EMPTY_MESSAGES'
export const CHANGE_SOCKET_STATUS = 'CHANGE_SOCKET_STATUS'
export const CLEAR_JOB_MESSAGES= 'CLEAR_JOB_MESSAGES'
export const CLEAR_WORKFLOW_MESSAGES= 'CLEAR_WORKFLOW_MESSAGES'


// export const CHANGE_SUBTASK_STATUS= 'CHANGE_SUBTASK_STATUS'

export const SET_WORKFLOWS = 'SET_WORKFLOWS'

export const SET_WORKFLOW = 'SET_WORKFLOW'
// export const DELETE_TASK ='DELETE_TASK'
